/*CREATE DATABASE bamazon;*/



/*CREATE TABLE products (
	ITEM_ID INTEGER(10) NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    DEPARTMENT_NAME VARCHAR(50) NOT NULL,
    CUSTOMER_COST FLOAT(8,2) NOT NULL,
    STOCK_QUANTITY INTEGER(10) NOT NULL,
    PRIMARY KEY (ITEM_ID)
);
*/
USE  bamazon;

INSERT INTO products (PRODUCT_NAME, DEPARTMENT_NAME, CUSTOMER_COST, STOCK_QUANTITY)
VALUES ("METAL DETECTOR", "ELECTRONICS", 249.99, 15), 
("SEWING NEEDLE", "DIY", 3.99, 1), 
("HAY BALE (100 LBS)", "PRODUCE", 7.79, 1000), 
("STAND MIXER", "KITCHENWARE", 399.99, 23), 
("STRANGE GOOP", "MISCELLANEOUS", 1.00, 8203),
("ILLEGAL WEAPONS", "WEAPONS", 399.45, 239), 
("NATIONAL TREASURE", "DVD", 19.99, 12903), 
("CARROTS (5 LB BAG)", "PRODUCE", 3.99, 3092), 
("HORSE", "LIVESTOCK", 2000.00, 5), 
("HOT GOODS", "MONEY", -3.28, 30), 
("CAN OPENER", "KITCENWARE", 9.99, 57);